package coordinaterecorder;
import java.io.*;
import javax.swing.JComponent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class MainWindow extends javax.swing.JFrame {
    
    CoordinateRecorder recorder;
            
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        headingLabel.setVisible(false);
        headingXPos.setVisible(false);
        headingXNeg.setVisible(false);
        headingYPos.setVisible(false);
        headingYNeg.setVisible(false);
        hereButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        AnchorBar = new javax.swing.JPanel();
        anchorPointLabel = new javax.swing.JLabel();
        addPointButton = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();
        headingXPos = new javax.swing.JButton();
        headingXNeg = new javax.swing.JButton();
        headingYPos = new javax.swing.JButton();
        headingYNeg = new javax.swing.JButton();
        anchorPanel = new javax.swing.JPanel();
        anchorPanel1 = new javax.swing.JPanel();
        anchorX1 = new javax.swing.JTextField();
        anchorY1 = new javax.swing.JTextField();
        anchorZ1 = new javax.swing.JTextField();
        setButton1 = new javax.swing.JButton();
        hereButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        headingButton = new javax.swing.JButton();
        markButton = new javax.swing.JButton();
        endButton = new javax.swing.JButton();
        toFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AIONAV Coordinate Recorder");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        AnchorBar.setLayout(new javax.swing.BoxLayout(AnchorBar, javax.swing.BoxLayout.LINE_AXIS));

        anchorPointLabel.setText("Anchor Points");
        AnchorBar.add(anchorPointLabel);

        addPointButton.setText("Add Point");
        addPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPointButtonActionPerformed(evt);
            }
        });
        AnchorBar.add(addPointButton);

        headingLabel.setText("Heading");

        headingXPos.setText("X+");

        headingXNeg.setText("X-");

        headingYPos.setText("Y+");

        headingYNeg.setText("Y-");

        anchorPanel1.setLayout(new javax.swing.BoxLayout(anchorPanel1, javax.swing.BoxLayout.LINE_AXIS));

        anchorX1.setText("x");
        anchorX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchorX1ActionPerformed(evt);
            }
        });
        anchorPanel1.add(anchorX1);

        anchorY1.setText("y");
        anchorY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchorY1ActionPerformed(evt);
            }
        });
        anchorPanel1.add(anchorY1);

        anchorZ1.setText("z");
        anchorPanel1.add(anchorZ1);

        setButton1.setText("Set A");
        setButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButton1ActionPerformed(evt);
            }
        });
        anchorPanel1.add(setButton1);

        hereButton1.setLabel("Here");
        hereButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hereButton1ActionPerformed(evt);
            }
        });
        anchorPanel1.add(hereButton1);

        javax.swing.GroupLayout anchorPanelLayout = new javax.swing.GroupLayout(anchorPanel);
        anchorPanel.setLayout(anchorPanelLayout);
        anchorPanelLayout.setHorizontalGroup(
            anchorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anchorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anchorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        anchorPanelLayout.setVerticalGroup(
            anchorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anchorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anchorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnchorBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headingLabel)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(headingXPos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(headingXNeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(headingYPos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(headingYNeg)))
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(anchorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(AnchorBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anchorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headingXPos)
                    .addComponent(headingXNeg)
                    .addComponent(headingYPos)
                    .addComponent(headingYNeg))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Distance from start to end: ");
        jPanel3.add(jLabel1);
        jPanel3.add(distanceLabel);

        getContentPane().add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton);

        headingButton.setText("Heading");
        headingButton.setEnabled(false);
        headingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(headingButton);

        markButton.setText("Mark");
        markButton.setEnabled(false);
        markButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markButtonActionPerformed(evt);
            }
        });
        jPanel1.add(markButton);

        endButton.setText("End");
        endButton.setEnabled(false);
        endButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endButtonActionPerformed(evt);
            }
        });
        jPanel1.add(endButton);

        toFileButton.setText("Save To File...");
        toFileButton.setEnabled(false);
        toFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(toFileButton);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        System.out.println("Start button clicked!");
        recorder = new CoordinateRecorder(textArea, distanceLabel);
        recorder.start();
        markButton.setEnabled(true);
        headingButton.setEnabled(true);
        endButton.setEnabled(true);
        startButton.setEnabled(false);
        System.out.println("test");
    }//GEN-LAST:event_startButtonActionPerformed

    private void toFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFileButtonActionPerformed
        String fileName = "logs/foot/log_" + System.currentTimeMillis() + ".txt";
        try {
            PrintWriter fw = new PrintWriter (new BufferedWriter (new FileWriter(fileName)));
            fw.write(textArea.getText());
            fw.flush();
            fw.close();
            System.out.println("Saved file");
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_toFileButtonActionPerformed

    private void endButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endButtonActionPerformed
        recorder.running = false;
        String fullText = textArea.getText();
        System.out.println(fullText);
        toFileButton.setEnabled(true);
        endButton.setEnabled(false);
        startButton.setEnabled(true);
    }//GEN-LAST:event_endButtonActionPerformed

    private void markButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markButtonActionPerformed
        // TODO add your handling code here: 
        //String mark = String.format("MARK%n");
        //textArea.append(mark);
        recorder.mark = true;
        System.out.println("test");
        recorder.getSegInfo();
    }//GEN-LAST:event_markButtonActionPerformed

    private void headingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headingButtonActionPerformed
        headingLabel.setVisible(true);
        headingXPos.setVisible(true);
        headingXNeg.setVisible(true);
        headingYPos.setVisible(true);
        headingYNeg.setVisible(true);
    }//GEN-LAST:event_headingButtonActionPerformed

    private void hereButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hereButton1ActionPerformed
        Double x = Double.parseDouble(anchorX1.getText());
        Double y = Double.parseDouble(anchorY1.getText());
        Double z = Double.parseDouble(anchorZ1.getText());
        textArea.append(String.format("x: %.3f y: %.3f z: %.3f%n", x, y, z));
        recorder.setAnchor(Double.parseDouble(anchorX1.getText()), Double.parseDouble(anchorY1.getText()));

    }//GEN-LAST:event_hereButton1ActionPerformed

    private void setButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButton1ActionPerformed
        anchorX1.setEnabled(false);
        anchorY1.setEnabled(false);
        hereButton1.setEnabled(true);
    }//GEN-LAST:event_setButton1ActionPerformed

    private void anchorY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchorY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchorY1ActionPerformed

    private void anchorX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchorX1ActionPerformed
        // TODO add your handling codet here:
    }//GEN-LAST:event_anchorX1ActionPerformed

    private void addPointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPointButtonActionPerformed
        System.out.println("In action performed");
        anchorPanel.add(new anchorPanel());
        ((JComponent)getContentPane()).revalidate();
        repaint();
    }//GEN-LAST:event_addPointButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnchorBar;
    private javax.swing.JButton addPointButton;
    private javax.swing.JPanel anchorPanel;
    private javax.swing.JPanel anchorPanel1;
    private javax.swing.JLabel anchorPointLabel;
    private javax.swing.JTextField anchorX1;
    private javax.swing.JTextField anchorY1;
    private javax.swing.JTextField anchorZ1;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JButton endButton;
    private javax.swing.JButton headingButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton headingXNeg;
    private javax.swing.JButton headingXPos;
    private javax.swing.JButton headingYNeg;
    private javax.swing.JButton headingYPos;
    private javax.swing.JButton hereButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markButton;
    private javax.swing.JButton setButton1;
    private javax.swing.JButton startButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JButton toFileButton;
    // End of variables declaration//GEN-END:variables
}
